# Generated by Django 3.2.7 on 2021-09-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singlepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranges',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
    ]
